const FETCH_DATA = "FETCH_DATA";
const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
const SELECT_COUNTRY = "SELECT_COUNTRY";
const ENTER_NUMBER = "ENTER_NUMBER";
const SELECT_OPERATOR = "SELECT_OPERATOR";
const SELECT_PRODUCT = "SELECT_PRODUCT";

export {
  FETCH_DATA,
  FETCH_DATA_SUCCESS,
  FETCH_DATA_FAILURE,
  SELECT_COUNTRY,
  ENTER_NUMBER,
  SELECT_OPERATOR,
  SELECT_PRODUCT,
};
